policy_path: "ckpt_demo/policy_roundhouse_kick.pt"
xml_path: "assets/robots/g1/g1_29dof_anneal_23dof.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.001
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 20

kps: [100, 100, 100, 200, 20, 20, 100, 100, 100, 200, 20, 20, 400, 400, 400, 90, 60, 20, 60, 90, 60, 20, 60]
kds: [2.5, 2.5, 2.5, 5.0, 0.2, 0.1, 2.5, 2.5, 2.5, 5.0, 0.2, 0.1, 5.0, 5.0, 5.0, 2.0, 1.0, 0.4, 1.0, 2.0, 1.0, 0.4, 1.0]
# kds: [2.5, 2.5, 2.5, 5.0, 0.2, 0.1, 2.5, 2.5, 2.5, 5.0, 0.2, 0.1, 5.0, 5.0, 5.0, 4.0, 2.0, 0.8, 2.0, 4.0, 2.0, 0.8, 2.0]

default_angles: [
                -0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                0.0, 0.0, 0.0, 
                0.4, 0.1, 0.0, 0.3,
                0.4, -0.1, 0.0, 0.3,]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
ref_joint_angles_scale: 1.0
ref_joint_velocities_scale: 1.0
num_actions: 23
num_obs: 122
frame_stack: 5

# dof_pos_lower_limit_list: [-2.5307, -0.5236, -2.7576, -0.087267, -0.87267, -0.2618, 
#                             -2.5307, -2.9671, -2.7576, -0.087267, -0.87267, -0.2618, 
#                             -2.618, -0.52, -0.52,
#                             -3.0892, -1.5882, -2.618, -1.0472, 
#                             -3.0892, -2.2515, -2.618, -1.0472]
dof_pos_lower_limit_list: [-2.5307, -0.5236, -2.7576, -0.087267, -100., -100., 
                            -2.5307, -2.9671, -2.7576, -0.087267, -100., -100., 
                            -2.618, -0.52, -0.52,
                            -3.0892, -1.5882, -2.618, -1.0472, 
                            -3.0892, -2.2515, -2.618, -1.0472]
dof_pos_upper_limit_list: [2.8798, 2.9671, 2.7576, 2.8798, 100., 100., 
                            2.8798, 0.5236, 2.7576, 2.8798, 100., 100., 
                            2.618, 0.52, 0.52,
                            2.6704, 2.2515, 2.618, 2.0944,
                            2.6704, 1.5882, 2.618, 2.0944]

dof_effort_limit_list: [88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
                          88.0, 88.0, 88.0, 139.0, 50.0, 50.0, 
                          88.0, 50.0, 50.0,
                          25.0, 25.0, 25.0, 25.0, 
                          25.0, 25.0, 25.0, 25.0]

motion:
  motion_file : 'data/motion_data/g1_LAFAN_roundhouse_kick.pkl'
  asset:
    assetRoot: "assets/robots/g1/"
    # assetFileName: "g1_29dof_anneal_23dof.xml"
    assetFileName: "g1_29dof_anneal_23dof_fitmotionONLY.xml"
    urdfFileName: "g1_29dof_anneal_23dof.urdf"

  humanoid_type: g1_29dof_anneal_23dof
  bias_offset: False
  has_self_collision: True
  has_mesh: False
  has_jt_limit: False
  has_dof_subset: True
  has_upright_start: True
  has_smpl_pd_offset: False
  remove_toe: False # For humanoid's geom toe
  motion_sym_loss: False
  sym_loss_coef: 1
  big_ankle: True

  has_shape_obs: false
  has_shape_obs_disc: false
  has_shape_variation: False

  masterfoot: False
  freeze_toe: false
  freeze_hand: False
  box_body: True
  real_weight: True
  real_weight_porpotion_capsules: True
  real_weight_porpotion_boxes: True

  body_names: ['pelvis', 
                'left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link', 
                'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link', 
                'waist_yaw_link', 'waist_roll_link', 'torso_link',
                'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link',
                'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']
        
  limb_weight_group: 
    - ['left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link']
    - ['right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link']
    - ['pelvis', 'waist_yaw_link', 'waist_roll_link', 'torso_link']
    - ['left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link']
    - ['right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

  dof_names: ['left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link', 
              'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link', 
              'waist_yaw_link', 'waist_roll_link', 'torso_link',
              'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link',
              'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']
  right_foot_name: 'r_foot_roll'
  left_foot_name: 'l_foot_roll'


  nums_extend_bodies: 3
  extend_config:
    - joint_name: "left_hand_link"
      parent_name: "left_elbow_link"
      pos: [0.25, 0.0, 0.0]
      rot: [1.0, 0.0, 0.0, 0.0] # w x y z
    - joint_name: "right_hand_link"
      parent_name: "right_elbow_link"
      pos: [0.25, 0.0, 0.0]
      rot: [1.0, 0.0, 0.0, 0.0] # w x y z
    - joint_name: "head_link"
      parent_name: "torso_link"
      pos: [0.0, 0.0, 0.42]
      rot: [1.0, 0.0, 0.0, 0.0] # w x y z


  motion_tracking_link:
    - "left_hand_link"
    - "right_hand_link"
    - "head_link"

  lower_body_link:
    - "pelvis"
    - "left_hip_pitch_link"
    - "left_hip_roll_link"
    - "left_hip_yaw_link"
    - "left_knee_link"
    - "left_ankle_pitch_link"
    - "left_ankle_roll_link"
    - "right_hip_pitch_link"
    - "right_hip_roll_link"
    - "right_hip_yaw_link"
    - "right_knee_link"
    - "right_ankle_pitch_link"
    - "right_ankle_roll_link"
    - "waist_yaw_link"
    - "waist_roll_link"
    - "torso_link"

  upper_body_link:
    - "left_shoulder_pitch_link"
    - "left_shoulder_roll_link"
    - "left_shoulder_yaw_link"
    - "left_elbow_link"
    - "right_shoulder_pitch_link"
    - "right_shoulder_roll_link"
    - "right_shoulder_yaw_link"
    - "right_elbow_link"
    - "left_hand_link"
    - "right_hand_link"
    - "head_link"


  pelvis_link: "pelvis"
  base_link: "torso_link"
  hips_link:
    - "left_hip_pitch_link"
    - "left_hip_roll_link"
    - "left_hip_yaw_link"
    - "right_hip_pitch_link"
    - "right_hip_roll_link"
    - "right_hip_yaw_link"
  
  joint_matches:
    - ["pelvis", "Pelvis"]
    - ["left_hip_pitch_link", "L_Hip"]
    - ["left_knee_link", "L_Knee"]
    - ["left_ankle_roll_link", "L_Ankle"]
    - ["right_hip_pitch_link", "R_Hip"]
    - ["right_knee_link", "R_Knee"]
    - ["right_ankle_roll_link", "R_Ankle"]
    - ["left_shoulder_roll_link", "L_Shoulder"]
    - ["left_elbow_link", "L_Elbow"]
    - ["left_hand_link", "L_Hand"]
    - ["right_shoulder_roll_link", "R_Shoulder"]
    - ["right_elbow_link", "R_Elbow"]
    - ["right_hand_link", "R_Hand"]
    - ["head_link", "Head"]


  smpl_pose_modifier:
    - Pelvis: "[np.pi/2, 0, np.pi/2]"
    - L_Shoulder: "[0, 0, -np.pi/2]"
    - R_Shoulder: "[0, 0, np.pi/2]"
    - L_Elbow: "[0, -np.pi/2, 0]"
    - R_Elbow: "[0, np.pi/2, 0]"

  visualization:
    customize_color : True
    marker_joint_colors : 
    - [0.929, 0.867, 0.437] # pelvis
    - [0.929, 0.867, 0.437] # left_hip_yaw_joint
    - [0.929, 0.867, 0.437] # left_hip_roll_joint
    - [0.929, 0.867, 0.437] # left_hip_pitch_joint
    - [0.929, 0.867, 0.437] # left_knee_joint
    - [0.929, 0.867, 0.437] # left_ankle_pitch_joint
    - [0.929, 0.867, 0.437] # left_ankle_roll_joint
    - [0.929, 0.867, 0.437] # right_hip_yaw_joint
    - [0.929, 0.867, 0.437] # right_hip_roll_joint
    - [0.929, 0.867, 0.437] # right_hip_pitch_joint
    - [0.929, 0.867, 0.437] # right_knee_joint
    - [0.929, 0.867, 0.437] # right_ankle_pitch_joint
    - [0.929, 0.867, 0.437] # right_ankle_roll_joint
    - [0.929, 0.867, 0.437] # waist_yaw_joint
    - [0.929, 0.867, 0.437] # waist_roll_joint
    - [0.929, 0.867, 0.437] # torso_joint (waist_pitch_link)
    - [0.929, 0.867, 0.437] # left_shoulder_pitch_joint
    - [0.929, 0.867, 0.437] # left_shoulder_roll_joint
    - [0.929, 0.867, 0.437] # left_shoulder_yaw_joint
    - [0.929, 0.867, 0.437] # left_elbow_joint
    - [0.929, 0.867, 0.437] # right_shoulder_pitch_joint
    - [0.929, 0.867, 0.437] # right_shoulder_roll_joint
    - [0.929, 0.867, 0.437] # right_shoulder_yaw_joint
    - [0.929, 0.867, 0.437] # right_elbow_joint
    - [0, 0.351, 0.613] # left_elbow_joint_extend
    - [0, 0.351, 0.613] # right_elbow_joint_extend
    - [0, 0.351, 0.613] # head_link